#Q1
#SELECT CUS_CODE, COUNT(DISTINCT INV_NUMBER) AS NUMBER of INVOICES,
#SUM(LINE_UNITS*LINE_PRICE) AS TOTAL CUSTOMER PURCHASES
#FROM INVOICE NATURAL JOIN LINE
#GROUP BY CUS_CODE

#2
#select CUS_CODE , COUNT(distinct INV_NUMBER) As number of invoices , 
 #sum(LINE_UNITS*LINE_PRICE) AS 'Total Customer Purchases '
 #from INVOICE NATURAL JOIN LINE 
 #group by CUS_CODE 
# ) as tbl;

#Q3
 #select CUS_CODE, CUS_BALANCE
 #from customer natural join invoice
 #group by CUS_CODE
 

 #Q4
 #SELECT MIN(CUS_BALANCE), MAX(CUS_BALANCE), AVG(CUS_BALANCE)
 #FROM(
 #SELECT DISTINCT CUS_CODE, CUS_BALANCE
 #FROM CUSTOMER NATURAL JOIN INVOICE
 #) AS TBL;

#Q5
select SUM(CUS_BALANCE),max(CUS_BALANCE),min(CUS_BALANCE), AVG(CUS_BALANCE)
from customer

#Q6
#select CUS_CODE, CUS_BALANCE 
#FROM CUSTOMER
#WHERE CUS_CODE NOT IN(
#SELECT CUS_CODE 
#FROM INVOICE
#)
#ORDER BY CUS_CODE




